import 'package:powersync/powersync.dart';

/// Schéma PowerSync aligné sur les tables Drift (`app_database.g.dart`).
///
/// Colonnes `dateTime` / `boolean` Drift → INTEGER SQLite.
/// `product_modifiers` (PK composite) est créée par Drift, pas par PowerSync.
/// `sync_queue` reste locale (LAN WebSocket, non répliquée cloud).
final Schema ritagestionPowerSyncSchema = Schema([
  _table('restaurant_config', [
    _t('name'),
    _t('address'),
    _t('phone'),
    _t('ice'),
    _t('rc'),
    _t('identifiant_fiscal'),
    _t('currency'),
    _t('logo_path'),
    _t('default_service_mode'),
    _dt('updated_at'),
  ]),
  _table('users', [
    _t('name'),
    _t('pin_hash'),
    _t('role'),
    _b('is_active'),
    _dt('created_at'),
    _dt('updated_at'),
  ]),
  _table('zones', [
    _t('name'),
    _i('sort_order'),
  ]),
  _table('restaurant_tables', [
    _t('zone_id'),
    _t('name'),
    _i('capacity'),
    _t('status'),
    _r('pos_x'),
    _r('pos_y'),
  ]),
  _table('reservations', [
    _t('table_id'),
    _t('customer_name'),
    _t('customer_phone'),
    _i('guest_count'),
    _dt('reserved_at'),
    _t('notes'),
    _t('status'),
    _dt('created_at'),
  ]),
  _table('time_attendance', [
    _t('user_id'),
    _dt('clock_in'),
    _dt('clock_out'),
    _t('notes'),
    _dt('created_at'),
  ]),
  _table('print_stations', [
    _t('name'),
    _t('ip_address'),
    _t('type'),
    _b('is_active'),
  ]),
  _table('categories', [
    _t('name'),
    _t('name_ar'),
    _t('image'),
    _t('color_hex'),
    _t('print_station_id'),
    _i('sort_order'),
    _t('scheduled_start_time'),
    _t('scheduled_end_time'),
    _b('is_active'),
  ]),
  _table('products', [
    _t('category_id'),
    _t('name'),
    _t('name_ar'),
    _t('barcode'),
    _r('price_dine_in'),
    _r('price_takeaway'),
    _r('price_delivery'),
    _r('cost'),
    _r('tax_rate'),
    _t('image'),
    _t('default_notes'),
    _b('track_stock'),
    _r('current_stock'),
    _i('sort_order'),
    _b('is_active'),
  ]),
  _table('modifier_groups', [
    _t('name'),
    _t('name_ar'),
    _b('is_multiple_choice'),
    _b('is_required'),
  ]),
  _table('modifier_options', [
    _t('modifier_group_id'),
    _t('name'),
    _t('name_ar'),
    _r('price_extra'),
    _i('sort_order'),
    _b('is_active'),
  ]),
  _table('ingredients', [
    _t('name'),
    _t('unit'),
    _r('cost_per_unit'),
    _r('current_stock'),
    _r('minimum_stock'),
    _dt('updated_at'),
  ]),
  _table('recipe_items', [
    _t('product_id'),
    _t('ingredient_id'),
    _r('quantity_used'),
  ]),
  _table('cash_sessions', [
    _t('cashier_id'),
    _dt('opened_at'),
    _dt('closed_at'),
    _r('opening_balance'),
    _r('closing_balance'),
    _r('expected_balance'),
    _t('closing_note'),
    _t('status'),
  ]),
  _table('cash_movements', [
    _t('session_id'),
    _t('user_id'),
    _t('type'),
    _r('amount'),
    _t('reason'),
    _dt('created_at'),
  ]),
  _table('orders', [
    _t('session_id'),
    _t('waiter_id'),
    _t('table_id'),
    _t('order_type'),
    _t('source'),
    _t('external_ref'),
    _t('status'),
    _t('discount_type'),
    _r('discount_value'),
    _t('discount_reason'),
    _t('discount_authorized_by'),
    _i('guest_count'),
    _t('notes'),
    _t('company_name'),
    _t('company_ice'),
    _i('invoice_number'),
    _dt('created_at'),
    _dt('updated_at'),
  ]),
  _table('order_items', [
    _t('order_id'),
    _t('product_id'),
    _r('quantity'),
    _r('unit_price'),
    _r('tax_rate'),
    _t('custom_notes'),
    _i('course_number'),
    _b('is_fired'),
    _t('status'),
    _t('void_reason'),
    _t('void_authorized_by'),
    _dt('created_at'),
  ]),
  _table('order_item_modifiers', [
    _t('order_item_id'),
    _t('modifier_option_id'),
    _r('price_extra'),
  ]),
  _table('discounts', [
    _t('name'),
    _t('type'),
    _r('value'),
    _t('code'),
    _i('max_uses'),
    _i('current_uses'),
    _dt('valid_from'),
    _dt('valid_until'),
    _b('is_active'),
  ]),
  _table('payments', [
    _t('order_id'),
    _t('payment_method'),
    _r('amount'),
    _t('reference'),
    _dt('paid_at'),
  ]),
  _table('audit_trail', [
    _t('user_id'),
    _t('action'),
    _t('target_type'),
    _t('target_id'),
    _t('details'),
    _dt('created_at'),
  ]),
  Table.localOnly('sync_queue', [
    _t('action'),
    _t('payload'),
    _t('status'),
    _i('retry_count'),
    _dt('created_at'),
    _dt('last_attempt_at'),
  ]),
]);

Table _table(String name, List<Column> columns) => Table(name, columns);

Column _t(String name) => Column.text(name);
Column _i(String name) => Column.integer(name);
Column _r(String name) => Column.real(name);
Column _dt(String name) => Column.integer(name);
Column _b(String name) => Column.integer(name);
